global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: rh-emea-sa-bot
    username: rh-emea-sa-bot
    email: rh.emea.sa.bot@gmail.com
    dev_revision: main

  quay:
    provider: quay.io
    account: rh_emea_sa_bot

  datacenter:
    clustername: cluster-qjgqf
    domain: qjgqf.sandbox2594.opentlc.com

  edge:
    clustername: cluster-qjgqf
    domain: qjgqf.sandbox2594.opentlc.com
